apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyperf.fullname" . }}
  namespace: {{ include "namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "hyperf.name" . }}
    helm.sh/chart: {{ include "hyperf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hyperf.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ include "hyperf.name" . }}
      version: v{{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hyperf.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "hyperf.name" . }}
        version: v{{ .Chart.AppVersion }}
        istio: monitor
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_ENV
              value: {{ .Chart.AppVersion }}
          envFrom:
            - secretRef:
                name: {{ template "hyperf.fullname" . }}-env
          ports:
            - name: http
              containerPort: 9501
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}