name: Testing process

on:
  push:
    branches: [ "main" ]

env:
  HYPERF_IMAGE: reinanhs/php-dev-8.2-swoole:latest

jobs:
  composer:
    runs-on: ubuntu-latest
    container:
      image: 'docker://${{ HYPERF_IMAGE }}'
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: composer install
      - name: Cache vendor
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor
  co-phpunit:
    runs-on: ubuntu-latest
    needs:
      - composer
    container:
      image: 'docker://${{ HYPERF_IMAGE }}'
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached vendor
        id: cache-vendor-restore
        uses: actions/cache/restore@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor
      - name: Test
        run: vendor/bin/co-phpunit --prepend test/bootstrap.php -c phpunit.xml
  coverage:
    runs-on: ubuntu-latest
    needs:
      - composer
      - co-phpunit
    container:
      image: "docker://$HYPERF_IMAGE"
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached vendor
        id: cache-vendor-restore
        uses: actions/cache/restore@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor
      - name: Test
        run: XDEBUG_MODE=coverage vendor/bin/co-phpunit --prepend test/bootstrap.php -c phpunit.xml --coverage-html cover/ --testsuite=u
      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: cover-page
          path: cover/
          retention-days: 1
